// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Produtos.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Produtos _$ProdutosFromJson(Map<String, dynamic> json) => Produtos(
      CODIGO: json['CODIGO'] as int?,
      NOME: json['NOME'] as String?,
      GRUPO: json['GRUPO'] as int?,
      MARCA: json['MARCA'] as int?,
      QTDEVENDA: json['QTDEVENDA'] as int?,
      QTDEPADRAO: json['QTDEPADRAO'] as int?,
      DESCRICAOEMBALAGEM: json['DESCRICAOEMBALAGEM'] as String?,
      FLEX: (json['FLEX'] as num?)?.toDouble(),
      QTDEMULTIPLA: (json['QTDEMULTIPLA'] as num?)?.toDouble(),
      QTDETROCA: json['QTDETROCA'] as int?,
      CODIGOBARRAS: json['CODIGOBARRAS'] as String?,
      FLEXFIXO: json['FLEXFIXO'] as String?,
      LIMITEINFERIORFLEX: (json['LIMITEINFERIORFLEX'] as num?)?.toDouble(),
      LIMITESUPERIORFLEX: (json['LIMITESUPERIORFLEX'] as num?)?.toDouble(),
      PROMOCAO: json['PROMOCAO'] as String?,
      REFERENCIA: json['REFERENCIA'] as String?,
      CODIGONCM: json['CODIGONCM'] as String?,
      ORDEM: json['ORDEM'] as int?,
      REQUERCOMBO: json['REQUERCOMBO'] as String?,
      PESOBRUTO: (json['PESOBRUTO'] as num?)?.toDouble(),
      PESOEMBALAGEM: (json['PESOEMBALAGEM'] as num?)?.toDouble(),
      QTDEMULTIPLAEMBALAGEM: json['QTDEMULTIPLAEMBALAGEM'] as int?,
      DESCONTOFIXO: (json['DESCONTOFIXO'] as num?)?.toDouble(),
      COMISSAO: (json['COMISSAO'] as num?)?.toDouble(),
      PMC: (json['PMC'] as num?)?.toDouble(),
      UNREFERENCIA: json['UNREFERENCIA'] as String?,
      QTDEREFERENCIA: (json['QTDEREFERENCIA'] as num?)?.toDouble(),
      PERCPOSITIVACAO: (json['PERCPOSITIVACAO'] as num?)?.toDouble(),
      ATIVO: json['ATIVO'] as String?,
      DESTACAR: json['DESTACAR'] as String?,
      MARGEMFLEXISENTA: (json['MARGEMFLEXISENTA'] as num?)?.toDouble(),
      CEST: json['CEST'] as String?,
      NOVO: json['NOVO'] as String?,
      TIPOPRODUTO: json['TIPOPRODUTO'] as int?,
      GERARFLEX: json['GERARFLEX'] as String?,
      VALORCUSTO: (json['VALORCUSTO'] as num?)?.toDouble(),
      QTDEMINIMA: (json['QTDEMINIMA'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$ProdutosToJson(Produtos instance) => <String, dynamic>{
      'CODIGO': instance.CODIGO,
      'NOME': instance.NOME,
      'GRUPO': instance.GRUPO,
      'MARCA': instance.MARCA,
      'QTDEVENDA': instance.QTDEVENDA,
      'QTDEPADRAO': instance.QTDEPADRAO,
      'DESCRICAOEMBALAGEM': instance.DESCRICAOEMBALAGEM,
      'FLEX': instance.FLEX,
      'QTDEMULTIPLA': instance.QTDEMULTIPLA,
      'QTDETROCA': instance.QTDETROCA,
      'CODIGOBARRAS': instance.CODIGOBARRAS,
      'FLEXFIXO': instance.FLEXFIXO,
      'LIMITEINFERIORFLEX': instance.LIMITEINFERIORFLEX,
      'LIMITESUPERIORFLEX': instance.LIMITESUPERIORFLEX,
      'PROMOCAO': instance.PROMOCAO,
      'REFERENCIA': instance.REFERENCIA,
      'CODIGONCM': instance.CODIGONCM,
      'ORDEM': instance.ORDEM,
      'REQUERCOMBO': instance.REQUERCOMBO,
      'PESOBRUTO': instance.PESOBRUTO,
      'PESOEMBALAGEM': instance.PESOEMBALAGEM,
      'QTDEMULTIPLAEMBALAGEM': instance.QTDEMULTIPLAEMBALAGEM,
      'DESCONTOFIXO': instance.DESCONTOFIXO,
      'COMISSAO': instance.COMISSAO,
      'PMC': instance.PMC,
      'UNREFERENCIA': instance.UNREFERENCIA,
      'QTDEREFERENCIA': instance.QTDEREFERENCIA,
      'PERCPOSITIVACAO': instance.PERCPOSITIVACAO,
      'ATIVO': instance.ATIVO,
      'DESTACAR': instance.DESTACAR,
      'MARGEMFLEXISENTA': instance.MARGEMFLEXISENTA,
      'CEST': instance.CEST,
      'NOVO': instance.NOVO,
      'TIPOPRODUTO': instance.TIPOPRODUTO,
      'GERARFLEX': instance.GERARFLEX,
      'VALORCUSTO': instance.VALORCUSTO,
      'QTDEMINIMA': instance.QTDEMINIMA,
    };
